apiVersion: v1
kind: Service
metadata:
    name: "volurkuber-b1ff"
    labels:
        app: "volurkuber-b1ff"
spec:
    type: LoadBalancer
    ports:
    - port: 443
      targetPort: 443
      protocol: TCP
      name: http
    selector:
        app: "volurkuber-b1ff"